language: php
php:
- 7.0
script:
- find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/lifterlms-wpmktgengine-extension/
  - secure: MJZLKy3j7zTjrt1EL6spW2/KjEHpX3rST6JT7U6q9EYPq5PY6G67QwEkGGvFiQ+vA46OXoJhq9F8KF9u112xM/bqcoqpnVpcHt3dtGD3jhYT6fjIOj8hB/kYFh3wxhVINrFGKpMAWxfpQFhhp6fmqjNqQVEJvXurZpi69UNstbptAoHodiwOEFIj3cYa4pEg9+1r+uvUKcNvIQwLFRPDiVOp+j/BjS9EBj5qOv6PgL7Xx1jqC6CLQrlawXPF1/ly1zJIHsp9tPf3BxowzcJ01FiXuSkhRh/7uAyWqrSMOd3LYgu6DDmtdbqrsAhegF1IB/LM//ghTDQS+2p+mHdz9/qE/ZgbI88zqfxwIwPYyCJR2FzRJce8Gzgs+RKo15QFocpAODpZCNyGKHh5DIkjZ7ri3eWZ/O7BDpTLb5QyPLHJ3YJ2hA0r/eCSQ3UiZzxPjCdyY1uqyNpn5HpueXiOHyDzje9u7Q/tTW1RJQap/MsuQjqDYlWHAPmSsKHCidwUxl2JItGQBxJqD5Z7i8OPn7Giikek65tGtIRqa60Pq5hH/y6PGSVs6RTEj3SPDSe/4+k+VExoUYivk/h1ngXyQQ9FU9gcMO95YHhMyoEcViELPzPaCmAMBPjDLuQ4/JK52OlyDXeaRKlTRn848v/65It5Som1kyflJPIedCb1dPA=
  - secure: Fn06r1XoZ4FxJrY9Q0gKzF1bji0TPWxsQRMINbkp26U3CFF5AIzCuJUtcmMcMPzEG4kIPhicsywCb6tMFZMtswNxiKJBSGZoGHk1gQH+QJZ6BB+BdlzYydHQggqg5KQS7A4DugIdzbt8dJm+Gy7jkzMnDJSxCI5W56BcoZCKIHAlNkmEXR2t4dde9ctlQ1GDr/AGwikG5yCI1+4X/8TcwRLR9DnAijSYQFsFI3ZVfRH790BO8DR4iy0zf4qNMrI+klqOc1GFZyWEsRnOQT+2lsGSzKE0ZvZwFtI6qq1cMFo0Y2b76w0aWorUVwN5AC6MRa102j7w8d9DCH/ZQmPuJKNnqP1ym25W09xy2IWMlyGBwsVrhQ9eAzGJkPq/DAJc8tE3N2zOWNvdu4Vr6ThNLHMomUFhINBfFhzEKf8hG1nrRmYWXOeq0regK2n5ATBWsyup5KK/GzaTq1360BuBCaN0EXAbV4E2Jmgb4WXIC8AALwXkUZIukI+RjIvQUEII9w38k4m9KObHF6e2VGGAgXrlNnHqWuTnyFdR0p1QXEL8xfz4Ll7wW53/MnuTsq8U1onwq9m/TN2Rrj2q+LOkQNexZ7+QY+ASkAVmY53j3kdc7NyElugTbj2Iicuzyo8FV6kwYJ3O2P710JOJEUcVwUQ9kJKY+xxUSbK9xXW9dW4=
notifications:
  slack:
    rooms:
    - secure: evgf1oVRfwFNSXdB4VxQlpUCcpUg3tjIj1dTQFfnTggYevwg5WrRwFWeb+sffdvDPlj6v68D42gxL2OBLOI9lG4NGaJ/9FZJ3LHIMTxRYokb5FqjYpj+3wrYWg8Wad370yboXZ2L77fYl4bM3nivkoDKflmeQLKswqhtrjvVzdiev+eTr1yoKTlr5oybEpaNM2XIbTTuUhmUzrHvLiSx4GaIr/tQvIhGcyiH5jKTAp2dMOg9lcgS5SHrwc+ldydQiLmYoxL2XZwsPYf0INKZfEAO8GSAL5mHAHlp9w8kSbJbd2sh9Vyiqlw+7OBg2zZnCr7NMcH8z50wN29uqd891nLciG80u12HeRZd8Ww/4j2N+SymN2J5Zehlr3ip0cMPT49d7H94uZxXZVIiA+TwhZaD8j0aoGIEZ3Ovm7NCSfwvtLLTQS1v1LuvuyCZw9+1GUzC7Qldc6xNhrxH2lQjD5Qbgd74mUHFOUkuEGXvtQmNTsTfTXgbwDStiHhU1WZofpDQw5hhhSWuDDS7Ie61vGDji2CNypLcEu6fnCb4aGzMaqO8Pd543UaWqkuJLNkfvf8kwVsp3vthidTNCdppykh6hPzZAIEhN48gEMUZRD6K0w5j6bywB5B38nekt498i6w4o4zOMx6nfQjc052+1YOvivuyoyq7KTEZr9xS2tU=
    on_success: always
    on_failure: always
